# Generated by Django 5.2.7 on 2026-09-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_inventario_promocion_remove_clientes_membresia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo',
            field=models.CharField(default='Estacional', max_length=50),
        ),
    ]
