# Generated by Django 5.2.7 on 2026-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_promocion_fecha_limite_promocion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
